In [1]:
import numpy as np

In [ ]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [ ]:
len(np.linspace(0,5,21))

21

The function numpy.eye(N, M=None, k=0, dtype=<class 'float'>) in the Numpy library is used to return a 2-D array with ones on the diagonal and zeros elsewhere. It's called eye because it represents the identity matrix I in linear algebra (the name refers to the "I" symbol).

The parameters are:
N: Number of rows in the output. It's an int and required.
M: Number of columns in the output. If None, defaults to N. It's optional and defaults to None.
k: Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. It's optional.
dtype: Data type of the returned array. It's optional and defaults to float.

In this example, we created a 3x3 identity matrix. As you can see, the matrix has 1's along the main diagonal and 0's everywhere else. This kind of matrix has special properties in linear algebra. For instance, any matrix (of suitable size) multiplied by an identity matrix will result in the original matrix.


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.33899126])

In [ ]:
np.random.rand(5,2)

array([[0.54034248, 0.11477984],
       [0.4817566 , 0.49317753],
       [0.05150231, 0.72944141],
       [0.53920979, 0.00954475],
       [0.2101407 , 0.35471822]])

In [ ]:
np.random.randn(10)

array([ 1.32142815, -0.98263815,  0.6211224 ,  0.69686749, -0.68615953,
       -0.61953136,  0.49473756, -1.73385989,  0.2490722 , -1.02249206])

In [ ]:
np.random.randn(2,3)

array([[-1.33112467, -0.63467199, -2.53966732],
       [ 1.20358491,  0.16288021, -2.43073001]])

In [ ]:
np.random.randint(0, 101, (4,5))

array([[ 0, 74, 78, 49, 55],
       [62, 24, 89, 34, 29],
       [35,  1, 20, 91, 27],
       [51, 88,  2, 16, 15]])

In [ ]:
np.random.randint(0, 101, 10)

array([21, 24, 46, 97, 56, 65, 50, 50,  1, 86])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.rand(4)

array([0.51182668, 0.69318953, 0.07093574, 0.29216544])

In [ ]:
arr = np.arange(0, 25)

In [ ]:
arr.reshape(5, 5) # 25 element fit into 5*5 shape 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr = np.random.randint(0, 101, 10)

In [ ]:
ranarr

array([43, 84, 48, 14, 23, 63, 65, 23,  9, 94])

In [ ]:
ranarr.max()

94

In [ ]:
ranarr.min()

9

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.argmin()

8

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0, 11)

In [14]:
slice_of_arr= arr[0:5]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d.shape

(3, 3)

In [29]:
arr_2d[2]

array([35, 40, 45])

In [32]:
arr_2d[2,2]

45

In [33]:
 arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [44]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr = np.arange(1,11)

In [46]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr>4

In [49]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
# np operations

In [53]:
arr = np.arange(0,10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [57]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr / arr

<ipython-input-61-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
1 / 0

ZeroDivisionError: ignored

In [63]:
1 / arr

<ipython-input-63-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [66]:
np.log(arr)

<ipython-input-66-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr.sum()

45

In [70]:
arr.mean()

4.5

In [71]:
arr.max()

9

In [72]:
arr.var()

8.25

In [73]:
arr.std()

2.8722813232690143

In [76]:
arr2d = np.arange(0,25).reshape(5,5)

In [77]:
arr2d.shape

(5, 5)

In [78]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr2d.sum()

300

In [81]:
arr2d.sum(axis=0) # perform operation across the rows

array([50, 55, 60, 65, 70])

In [82]:
arr2d.sum(axis=1) # perform operation across the columns

array([ 10,  35,  60,  85, 110])