In [2]:
import numpy as np

In [4]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [5]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [12]:
len(np.linspace(0,5,21))

21

The function numpy.eye(N, M=None, k=0, dtype=<class 'float'>) in the Numpy library is used to return a 2-D array with ones on the diagonal and zeros elsewhere. It's called eye because it represents the identity matrix I in linear algebra (the name refers to the "I" symbol).

The parameters are:
N: Number of rows in the output. It's an int and required.
M: Number of columns in the output. If None, defaults to N. It's optional and defaults to None.
k: Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. It's optional.
dtype: Data type of the returned array. It's optional and defaults to float.

In this example, we created a 3x3 identity matrix. As you can see, the matrix has 1's along the main diagonal and 0's everywhere else. This kind of matrix has special properties in linear algebra. For instance, any matrix (of suitable size) multiplied by an identity matrix will result in the original matrix.


In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand(1)

array([0.33899126])

In [20]:
np.random.rand(5,2)

array([[0.54034248, 0.11477984],
       [0.4817566 , 0.49317753],
       [0.05150231, 0.72944141],
       [0.53920979, 0.00954475],
       [0.2101407 , 0.35471822]])

In [21]:
np.random.randn(10)

array([ 1.32142815, -0.98263815,  0.6211224 ,  0.69686749, -0.68615953,
       -0.61953136,  0.49473756, -1.73385989,  0.2490722 , -1.02249206])

In [22]:
np.random.randn(2,3)

array([[-1.33112467, -0.63467199, -2.53966732],
       [ 1.20358491,  0.16288021, -2.43073001]])

In [23]:
np.random.randint(0, 101, (4,5))

array([[ 0, 74, 78, 49, 55],
       [62, 24, 89, 34, 29],
       [35,  1, 20, 91, 27],
       [51, 88,  2, 16, 15]])

In [24]:
np.random.randint(0, 101, 10)

array([21, 24, 46, 97, 56, 65, 50, 50,  1, 86])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [4]:
np.random.rand(4)

array([0.51182668, 0.69318953, 0.07093574, 0.29216544])

In [6]:
arr = np.arange(0, 25)

In [8]:
arr.reshape(5, 5) # 25 element fit into 5*5 shape 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
ranarr = np.random.randint(0, 101, 10)

In [10]:
ranarr

array([43, 84, 48, 14, 23, 63, 65, 23,  9, 94])

In [11]:
ranarr.max()

94

In [12]:
ranarr.min()

9

In [13]:
ranarr.argmax()

9

In [14]:
ranarr.argmin()

8

In [15]:
ranarr.dtype

dtype('int64')

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.shape

(25,)

In [18]:
arr = arr.reshape(5,5)

In [19]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.shape

(5, 5)

In [21]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [22]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])